spring:
  application:
    name: warehouse

warehouse:
  udp:
    host: 127.0.0.1
  sensor:
    temperature:
      port: 3344
      type: temperature
    humidity:
      port: 3355
      type: humidity